"""
AI Sim Racing Coach - Demo Telemetry Generator
Generates realistic GT3 car telemetry for Spa-Francorchamps circuit
"""

import json
import time
import math
import random
from dataclasses import dataclass, asdict
from typing import List, Dict
from datetime import datetime


@dataclass
class TelemetryFrame:
    """Single telemetry frame matching common sim racing data"""
    timestamp: float
    
    # Basic
    speed: float  # km/h
    rpm: int
    gear: int
    max_rpm: int = 8500
    
    # Position
    lap_distance: float  # 0.0 to 1.0 (percentage around track)
    lap_time: float  # current lap time in seconds
    lap_number: int
    last_lap_time: float  # seconds
    best_lap_time: float  # seconds
    
    # Inputs
    throttle: float  # 0.0 to 1.0
    brake: float  # 0.0 to 1.0
    clutch: float  # 0.0 to 1.0
    steering: float  # -1.0 to 1.0
    
    # Forces
    g_force_lateral: float
    g_force_longitudinal: float
    g_force_vertical: float
    
    # Tires (FL, FR, RL, RR)
    tire_temp_fl: float
    tire_temp_fr: float
    tire_temp_rl: float
    tire_temp_rr: float
    
    tire_pressure_fl: float
    tire_pressure_fr: float
    tire_pressure_rl: float
    tire_pressure_rr: float
    
    tire_wear_fl: float  # 0.0 (new) to 1.0 (worn)
    tire_wear_fr: float
    tire_wear_rl: float
    tire_wear_rr: float
    
    # Brakes
    brake_temp_fl: float
    brake_temp_fr: float
    brake_temp_rl: float
    brake_temp_rr: float
    
    # Engine/Fuel
    oil_temp: float
    water_temp: float
    fuel_level: float  # 0.0 to 1.0
    fuel_remaining_laps: float
    
    # Session
    session_type: str  # "Practice", "Qualifying", "Race"
    track_temp: float
    air_temp: float
    
    # Flags/Warnings
    yellow_flag: bool = False
    blue_flag: bool = False
    pit_limiter: bool = False
    
    # AI Coaching (generated by rules engine)
    coaching_messages: List[str] = None


class SpaCircuit:
    """Spa-Francorchamps circuit definition with corners"""
    
    TRACK_LENGTH = 7004  # meters
    CORNERS = [
        # (distance_pct, name, apex_speed_kmh, brake_zone)
        (0.05, "La Source", 85, True),
        (0.15, "Eau Rouge", 220, False),
        (0.18, "Raidillon", 200, False),
        (0.28, "Les Combes", 110, True),
        (0.35, "Malmedy", 130, True),
        (0.42, "Rivage", 95, True),
        (0.50, "Pouhon", 145, True),
        (0.58, "Campus", 140, True),
        (0.62, "Stavelot", 110, True),
        (0.70, "Blanchimont", 270, False),
        (0.85, "Bus Stop Chicane", 90, True),
    ]
    
    @staticmethod
    def get_sector(lap_distance: float) -> int:
        """Get sector number (1-3) based on lap distance"""
        if lap_distance < 0.33:
            return 1
        elif lap_distance < 0.67:
            return 2
        else:
            return 3


class GT3TelemetrySimulator:
    """Simulates realistic GT3 car telemetry"""
    
    def __init__(self):
        self.lap_number = 1
        self.lap_distance = 0.0
        self.lap_time = 0.0
        self.best_lap_time = 999.0
        self.last_lap_time = 0.0
        
        # Initial conditions
        self.tire_temp_base = 75.0  # Celsius
        self.tire_wear_total = 0.0
        self.fuel_level = 1.0
        self.brake_temp_base = 300.0
        
        self.current_corner_idx = 0
        self.session_type = "Race"
        
    def generate_frame(self, delta_time: float = 0.016) -> TelemetryFrame:
        """Generate single telemetry frame (60 FPS = ~0.016s)"""
        
        # Update lap progress
        current_speed = self._calculate_speed()
        distance_traveled = (current_speed / 3.6) * delta_time  # m/s
        self.lap_distance += distance_traveled / SpaCircuit.TRACK_LENGTH
        self.lap_time += delta_time
        
        # Lap completion
        if self.lap_distance >= 1.0:
            self.lap_distance -= 1.0
            self.last_lap_time = self.lap_time
            if self.lap_time < self.best_lap_time:
                self.best_lap_time = self.lap_time
            self.lap_time = 0.0
            self.lap_number += 1
            
        # Find nearest corner
        nearest_corner = min(
            SpaCircuit.CORNERS,
            key=lambda c: abs(c[0] - self.lap_distance)
        )
        
        # Calculate inputs based on position
        throttle, brake, steering = self._calculate_inputs(nearest_corner)
        
        # Calculate forces
        g_lat, g_lon, g_vert = self._calculate_g_forces(throttle, brake, steering)
        
        # Tire physics
        tire_temps = self._calculate_tire_temps(g_lat, brake)
        tire_pressures = self._calculate_tire_pressures(tire_temps)
        tire_wear = self._calculate_tire_wear()
        
        # Brake temps
        brake_temps = self._calculate_brake_temps(brake, current_speed)
        
        # Engine
        gear = self._calculate_gear(current_speed)
        rpm = self._calculate_rpm(current_speed, gear)
        
        # Fuel
        self.fuel_level -= 0.00001 * (throttle + 0.1)  # consumption
        fuel_laps = self.fuel_level * 25.0  # ~25 laps on full tank
        
        # Generate coaching messages
        coaching = self._generate_coaching(
            tire_temps, brake_temps, throttle, brake, self.lap_time, nearest_corner
        )
        
        return TelemetryFrame(
            timestamp=time.time(),
            speed=current_speed,
            rpm=rpm,
            gear=gear,
            lap_distance=self.lap_distance,
            lap_time=self.lap_time,
            lap_number=self.lap_number,
            last_lap_time=self.last_lap_time if self.last_lap_time > 0 else 999.0,
            best_lap_time=self.best_lap_time,
            throttle=throttle,
            brake=brake,
            clutch=0.0,
            steering=steering,
            g_force_lateral=g_lat,
            g_force_longitudinal=g_lon,
            g_force_vertical=g_vert,
            tire_temp_fl=tire_temps[0],
            tire_temp_fr=tire_temps[1],
            tire_temp_rl=tire_temps[2],
            tire_temp_rr=tire_temps[3],
            tire_pressure_fl=tire_pressures[0],
            tire_pressure_fr=tire_pressures[1],
            tire_pressure_rl=tire_pressures[2],
            tire_pressure_rr=tire_pressures[3],
            tire_wear_fl=tire_wear[0],
            tire_wear_fr=tire_wear[1],
            tire_wear_rl=tire_wear[2],
            tire_wear_rr=tire_wear[3],
            brake_temp_fl=brake_temps[0],
            brake_temp_fr=brake_temps[1],
            brake_temp_rl=brake_temps[2],
            brake_temp_rr=brake_temps[3],
            oil_temp=95.0 + random.uniform(-2, 2),
            water_temp=82.0 + random.uniform(-1, 1),
            fuel_level=self.fuel_level,
            fuel_remaining_laps=fuel_laps,
            session_type=self.session_type,
            track_temp=28.0,
            air_temp=22.0,
            coaching_messages=coaching
        )
    
    def _calculate_speed(self) -> float:
        """Calculate speed based on track position"""
        # Find nearest corner
        nearest_corner = min(
            SpaCircuit.CORNERS,
            key=lambda c: abs(c[0] - self.lap_distance)
        )
        
        distance_to_corner = abs(nearest_corner[0] - self.lap_distance)
        
        if distance_to_corner < 0.02:  # At corner
            return nearest_corner[2] + random.uniform(-5, 5)
        elif distance_to_corner < 0.05:  # Approaching or exiting
            # Braking or accelerating
            if self.lap_distance < nearest_corner[0]:  # Approaching
                return 200 + random.uniform(-10, 10)
            else:  # Exiting
                return 180 + random.uniform(-10, 10)
        else:  # Straight
            return 280 + random.uniform(-10, 10)
    
    def _calculate_inputs(self, nearest_corner) -> tuple:
        """Calculate throttle, brake, steering"""
        distance_to_corner = abs(nearest_corner[0] - self.lap_distance)
        
        if distance_to_corner < 0.01 and self.lap_distance < nearest_corner[0]:
            # Braking zone
            throttle = 0.0
            brake = 0.8 + random.uniform(-0.1, 0.1)
            steering = random.uniform(-0.3, 0.3)
        elif distance_to_corner < 0.015:
            # Corner apex
            throttle = 0.3 + random.uniform(0, 0.3)
            brake = 0.0
            steering = 0.6 if random.random() > 0.5 else -0.6
            steering += random.uniform(-0.1, 0.1)
        elif distance_to_corner < 0.03:
            # Corner exit
            throttle = 0.9 + random.uniform(-0.1, 0.1)
            brake = 0.0
            steering = 0.3 if random.random() > 0.5 else -0.3
        else:
            # Straight
            throttle = 1.0
            brake = 0.0
            steering = random.uniform(-0.05, 0.05)
        
        return throttle, brake, steering
    
    def _calculate_g_forces(self, throttle, brake, steering) -> tuple:
        """Calculate G-forces"""
        g_lat = steering * 2.5 + random.uniform(-0.1, 0.1)
        g_lon = (throttle * 1.2) - (brake * 2.8) + random.uniform(-0.1, 0.1)
        g_vert = 1.0 + random.uniform(-0.05, 0.05)
        return g_lat, g_lon, g_vert
    
    def _calculate_tire_temps(self, g_lat, brake) -> list:
        """Calculate tire temperatures"""
        # Front tires work harder in GT3
        base_temp = self.tire_temp_base
        
        fl_temp = base_temp + 5 + abs(g_lat) * 10 + random.uniform(-3, 3)
        fr_temp = base_temp + 5 + abs(g_lat) * 10 + random.uniform(-3, 3)
        rl_temp = base_temp + random.uniform(-3, 3)
        rr_temp = base_temp + random.uniform(-3, 3)
        
        # Heat from braking
        fl_temp += brake * 5
        fr_temp += brake * 5
        
        # Gradually increase base temp (tire warm-up)
        self.tire_temp_base = min(95.0, base_temp + 0.001)
        
        return [fl_temp, fr_temp, rl_temp, rr_temp]
    
    def _calculate_tire_pressures(self, tire_temps) -> list:
        """Calculate tire pressures (increases with temp)"""
        base_pressure = 27.5  # PSI
        return [
            base_pressure + (temp - 75.0) * 0.05 + random.uniform(-0.1, 0.1)
            for temp in tire_temps
        ]
    
    def _calculate_tire_wear(self) -> list:
        """Calculate tire wear"""
        self.tire_wear_total += 0.00001
        wear = self.tire_wear_total
        
        # Front tires wear more
        return [
            min(1.0, wear * 1.2 + random.uniform(0, 0.01)),
            min(1.0, wear * 1.2 + random.uniform(0, 0.01)),
            min(1.0, wear + random.uniform(0, 0.01)),
            min(1.0, wear + random.uniform(0, 0.01)),
        ]
    
    def _calculate_brake_temps(self, brake, speed) -> list:
        """Calculate brake temperatures"""
        base = self.brake_temp_base
        heat_input = brake * (speed / 100.0) * 50
        
        # Cool down when not braking
        self.brake_temp_base = max(200.0, base - 0.5 + heat_input)
        
        fl = base + heat_input + random.uniform(-10, 10)
        fr = base + heat_input + random.uniform(-10, 10)
        rl = base + heat_input * 0.6 + random.uniform(-10, 10)
        rr = base + heat_input * 0.6 + random.uniform(-10, 10)
        
        return [fl, fr, rl, rr]
    
    def _calculate_gear(self, speed_kmh) -> int:
        """Calculate gear based on speed"""
        if speed_kmh < 60:
            return 2
        elif speed_kmh < 100:
            return 3
        elif speed_kmh < 140:
            return 4
        elif speed_kmh < 180:
            return 5
        elif speed_kmh < 220:
            return 6
        else:
            return 7
    
    def _calculate_rpm(self, speed_kmh, gear) -> int:
        """Calculate RPM based on speed and gear"""
        base_rpm = 3000 + (speed_kmh * 20)
        gear_modifier = (8 - gear) * 500
        return int(min(8500, base_rpm + gear_modifier + random.uniform(-100, 100)))
    
    def _generate_coaching(self, tire_temps, brake_temps, throttle, brake, 
                          lap_time, nearest_corner) -> List[str]:
        """Generate AI coaching messages based on telemetry"""
        messages = []
        
        # Tire temperature warnings
        avg_tire_temp = sum(tire_temps) / len(tire_temps)
        if avg_tire_temp > 105:
            messages.append("⚠️ TIRE OVERHEAT: Reduce aggression, tires above 105°C")
        elif avg_tire_temp < 70:
            messages.append("ℹ️ Tires cold: Push harder to build temperature")
        
        # Brake temperature
        avg_brake_temp = sum(brake_temps) / len(brake_temps)
        if avg_brake_temp > 800:
            messages.append("🔥 BRAKE OVERHEAT: Reduce brake pressure, risk of fade")
        elif avg_brake_temp > 700:
            messages.append("⚠️ High brake temps: Consider cooling lap")
        
        # Throttle technique
        if throttle > 0.1 and brake > 0.1:
            messages.append("⚠️ TRAIL BRAKING: Overlapping brake/throttle detected")
        
        # Corner-specific coaching
        corner_name = nearest_corner[1]
        distance = abs(nearest_corner[0] - self.lap_distance)
        
        if distance < 0.02:
            if corner_name == "Eau Rouge":
                if throttle < 0.9:
                    messages.append(f"💡 {corner_name}: You can take this flat out!")
            elif corner_name == "Pouhon":
                messages.append(f"🎯 {corner_name}: Focus on smooth steering input")
        
        # Lap time comparison
        if self.best_lap_time < 999 and lap_time > self.best_lap_time + 2:
            messages.append(f"📊 Currently {lap_time - self.best_lap_time:.2f}s off best lap")
        
        return messages


def main():
    """Demo: Generate and print telemetry frames"""
    simulator = GT3TelemetrySimulator()
    
    print("=" * 80)
    print("AI Sim Racing Coach - Demo Telemetry Generator")
    print("Circuit: Spa-Francorchamps | Car: GT3 | Session: Race")
    print("=" * 80)
    print()
    
    try:
        for i in range(100):  # Generate 100 frames (~1.6 seconds)
            frame = simulator.generate_frame()
            
            # Print summary every 10 frames
            if i % 10 == 0:
                print(f"\n--- Frame {i} | Lap {frame.lap_number} ---")
                print(f"Speed: {frame.speed:.1f} km/h | Gear: {frame.gear} | RPM: {frame.rpm}")
                print(f"Position: {frame.lap_distance*100:.1f}% | Lap Time: {frame.lap_time:.2f}s")
                print(f"Throttle: {frame.throttle*100:.0f}% | Brake: {frame.brake*100:.0f}%")
                print(f"Tire Temps (FL/FR/RL/RR): {frame.tire_temp_fl:.1f}°C / {frame.tire_temp_fr:.1f}°C / {frame.tire_temp_rl:.1f}°C / {frame.tire_temp_rr:.1f}°C")
                print(f"G-Forces (Lat/Lon): {frame.g_force_lateral:.2f}g / {frame.g_force_longitudinal:.2f}g")
                
                if frame.coaching_messages:
                    print(f"\n🤖 AI Coach:")
                    for msg in frame.coaching_messages:
                        print(f"   {msg}")
            
            time.sleep(0.016)  # 60 FPS
            
    except KeyboardInterrupt:
        print("\n\nDemo stopped by user")
        print(f"Final Stats:")
        print(f"  Laps completed: {simulator.lap_number - 1}")
        print(f"  Best lap time: {simulator.best_lap_time:.2f}s")
        print(f"  Fuel remaining: {simulator.fuel_level*100:.1f}%")


if __name__ == "__main__":
    main()
